### PR TITLE
Use Start/End instead of Left/Right to support RTL

### PR DESCRIPTION
**Pull request by kekkyojin**
## PR Checklist

Please check all that apply to this PR using "x":

- [x] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [x] I have checked that this PR does not introduce a breaking change
- [ ] This PR introduces breaking changes and I have provided a detailed explanation below

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting)
- [ ] Refactoring (no functional changes)
- [ ] Documentation changes
- [ ] Other - Please describe:

## Fixes

Issue   Number: #999 

## What is the current behavior?
Code was using API methods which weren't RTL-aware.
## What is the new behavior?
Code is using methods and view properties which are RTL-aware

### CODE REVIEW

**Comment by kauffj** [comment]
great fix @kekkyojin!

**Comment by akinwale** [comment]
@kekkyojin This is great, thanks! Is there an easy way to test the RTL display that doesn't involve changing the device language?

**Comment by kekkyojin** [comment]
Sure, @akinwale. On Android Studio, select the Split or the Design view on any layout XML file. Then go to the language selection menu list. That would normally read "Default (en-us)". The last item on the list reads "Preview Right to Left". Views will move to their new positions in real time when selected.

That was the way I tested the second commit on this PR.

**Review by akinwale — APPROVED** [review]
Looks good. Thanks.

**Pull request merged**
