### PR TITLE
Add open.lbry.com deep-links

### PR DESCRIPTION
**Pull request by kekkyojin**
PR Checklist

Please check all that apply to this PR using "x":

- [x] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [x] I have checked that this PR does not introduce a breaking change
- [ ] This PR introduces breaking changes and I have provided a detailed explanation below

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting)
- [ ] Refactoring (no functional changes)
- [ ] Documentation changes
- [ ] Other - Please describe:

## Fixes

Issue Number: #957 

## What is the current behavior?
LBRY Android is not offered when user clicks on open.lbry.com links.

## What is the new behavior?
LBRY Android will show on lists of apps which can manage open.lbry.com links
## Other information
It adds itself for intents with an '`https://`" protocol schema and an '`open.lbry.com`' host on AndroidManifest.

When system observes an intent from user to visit any link of the form `https://open.lbry.com:`, it will show a dialog with a list of all apps registered for that intent. When user selects LBRY app, the system will open it and it will recieve the link, which this PR will transform into something like an lbry:// intent, instead of managing it separatelly.

It modifies regex parts as following:

* Add 'https' as a possible option for protocol part
* Add a HOST regex part which could only be empty or open.lbry.com

It shifts components for matched strings as a new host component has been added.

In case host part is the expected 'open.lbry.com', it will change separators from ':' to '#'. This is also commented on code.

### Note for merger
Maybe this PR could be delayed for next 0.16 release or even a future one as it adds a new feature and not a bug-fix. Until then, I will be attending any change requested by the reviewer.

### CODE REVIEW

**Comment by kauffj** [comment]
Sweet!! :grin:

**Comment by tzarebczan** [comment]
This is awesome, thanks so much! We'll get it reviewed soon. Can we show you some [appreciation](https://lbry.com/faq/appreciation) for the contribution?

**Comment by kekkyojin** [comment]
Not at this time, but thank you anyway.

**Comment by kekkyojin** [comment]
With deep links, user has always the choice about which app to use. If lbry.tv was added, user would also be offered a dialog box and then it could select a web browser or LBRY. But, yes, I also think that lbry.tv could better be left to the web browser experience. At the end, creators will choose one or another, and I think they will be choosing the lbry.tv one.

**Comment by tzarebczan** [comment]
Yea,I think we should support lbry.tv as well. Many people share those links and would still expect to open in app if available.

**Pull request merged**
