### PR TITLE
Removed comment tips

### PR DESCRIPTION
**Pull request by clay53**
## PR Checklist

Please check all that apply to this PR using "x":

- [x] I have checked that this PR is not a duplicate of an existing PR (open, closed or merged)
- [x] I have checked that this PR does not introduce a breaking change
- [ ] This PR introduces breaking changes and I have provided a detailed explanation below

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting)
- [ ] Refactoring (no functional changes)
- [ ] Documentation changes
- [ ] Other - Please describe:

## Fixes

Issue Number: #1042 

## What is the current behavior?
Comments requires a 1 LBC top to be paid

## What is the new behavior?
Commenting does not require any tip to be paid

## Other information
Not sure if warning that comment will be posted should be removed entirely or not. Will remove if asked.

### CODE REVIEW

**Comment by kekkyojin** [comment]
This PR removes or refactor a lot of methods which would need to be added again if in the future LBRY decides to require users to pay for commenting. Wouldn't it be better to just change the price in code to 0 and ensure strings are able to adapt to a free-to-comment context?

**Comment by clay53** [comment]
> This PR removes or refactor a lot of methods which would need to be added again if in the future LBRY decides to require users to pay for commenting. Wouldn't it be better to just change the price in code to 0 and ensure strings are able to adapt to a free-to-comment context?

If there are no thoughts about adding back paying for comments (and I'm not sure why there would be), removing the functionality entirely is more efficient. If someone from the core team wants me to do what you suggested, I'll change it.

**Comment by akinwale** [comment]
We were planning to eventually remove tip to comment functionality completely, so this PR is pretty useful.

**Review by akinwale — APPROVED** [review]
Thanks for this.

**Pull request merged**
