### PR TITLE
DOCKER-CI: Dockerfile and build script for Continuous Integration

### PR DESCRIPTION
**Pull request by EnigmaCurry**
A docker-ized APK builder for lbry-android.

See included DOCKER-CI.md for details.

### CODE REVIEW

**Comment by EnigmaCurry** [comment]
(sorry, force-pushed a few times to fix typos in readme. I'm done now :) )

**Comment by EnigmaCurry** [comment]
Also, I'm using a docker base image here: https://github.com/PlenusPyramis/AndroidSDK

I saw there is a lbry/android-base image on docker hub, but not knowing it's origin (It's not a public automated build like the one above), I chose not to use it. This could be switched back to a lbry controlled image but would prefer it be a public build.

**Comment by kauffj** [comment]
Hopefully this is useful to @akinwale in terms of his CI/build process. 

Is the limitation just for EXT4, so we should expect it to work on Windows/macOS?

(I'm on EXT4 so it's of limited value to me personally and I suppose I'll go back to trying the manual steps again)

**Comment by EnigmaCurry** [comment]
Thank you! I think your Dockerfile is largely equivalent to the one I have here, unless you see anything out of place.

**Comment by EnigmaCurry** [comment]
Don't merge this PR, I've broken the base image working on my local-dev workflow. I will open a new PR soon.

**Pull request closed without merging**
