### PR TITLE
DOCKER-DEV: Local development in a docker container

### PR DESCRIPTION
**Pull request by EnigmaCurry**
This encapsulates all the docker commands into a single bash CLI script for a local development environment.

This successfully builds the apk and provides instructions for connecting a real android device via adb for testing with hot-reload.

README: https://github.com/EnigmaCurry/lbry-android/blob/docker-build/DOCKER-DEV.md

### CODE REVIEW

**Comment by EnigmaCurry** [comment]
lbry-android is ARM only, so the x86 emulator won't work. The ARM emulator is way too slow to be usable. So I think I'm dropping the emulator feature.

**Comment by akinwale** [comment]
@EnigmaCurry The React Native codebase was moved to a separate repository, and is now handled as a submodule, so we need to add a line to initialise submodules after cloning the `lbry-android` repo.

`git submodule update --init --recursive`

**Comment by kauffj** [comment]
@akinwale can you just add that yourself and merge?

**Comment by EnigmaCurry** [comment]
Added.

**Pull request merged**
